language: bash

env:
  - SLEEP=30
  - SLEEP=60
  - SLEEP=90
  - SLEEP=120
  - SLEEP=180
  - SLEEP=240
  - SLEEP=300
  - SLEEP=360
    # 10+ minutes
  - SLEEP=660 KEEPALIVE=false SHOULDERROR=true
  - SLEEP=880 KEEPALIVE=false SHOULDERROR=true
  - SLEEP=1760 KEEPALIVE=false SHOULDERROR=true
  - SLEEP=3520 KEEPALIVE=false SHOULDERROR=true
  - SLEEP=7040 KEEPALIVE=false SHOULDERROR=true
  - SLEEP=10000 KEEPALIVE=false SHOULDERROR=true
    # 2+ hours
  - SLEEP=7260 KEEPALIVE=true SHOULDERROR=true
  - SLEEP=7260 KEEPALIVE=false SHOULDERROR=true
 
matrix:
  - fast_finish: false
  - allow_failures:
    - SLEEP=660 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=880 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=1760 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=3520 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=7040 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=10000 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=7260 KEEPALIVE=true SHOULDERROR=true
    - SLEEP=7260 KEEPALIVE=false SHOULDERROR=true

before_install:
  - which cowsay
  - curl icanhazip.com
  - uptime
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  #- sudo apt --option Acquire::http::Timeout="20" update -q
  #- sudo apt --option Acquire::http::Timeout="20" install gcc-4.8 -y
  #- sudo apt --option Acquire::http::Timeout="20" install jq traceroute -y

addons:
  apt:
    #sources:
      #- sourceline: 'deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty main'
    packages:
      - jq
      - traceroute
      - cowsay

before_script:
  - echo 'export PATH="/usr/games:$PATH"' >> .profile
  - source .profile
  - curl icanhazip.com
  - uptime

script: ./sleep.sh $SLEEP

after_script:
  - cat ~/apt-get-update.log
  - cowsay "Alles gut!"

notifications:
  webhooks: http://requestbin.fullcontact.com/1h1yzk51
