language: bash
sudo: required

#env:
  #- SLEEP=10000 KEEPALIVE=false SHOULDERROR=true
    # 2+ hours
  #- SLEEP=7260 KEEPALIVE=true SHOULDERROR=true
  #- SLEEP=7260 KEEPALIVE=false SHOULDERROR=true

before_script:
  - sudo docker info
  - sudo cat /etc/default/docker
  - /etc/init.d/docker status
  - ls -la /etc/init.d
  - cat /etc/init.d/docker
  - sudo ls -lahF /etc/docker
  - ps -fp $(pidof dockerd)
  - env
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --registry-mirror "http://staging-1-docker-registry.gce-us-central1.travisci.net"' | sudo tee -a /etc/default/docker
  - sudo service docker restart
  - ps -fp $(pidof dockerd)
  #- dockerd --registry-mirror "http://staging-1-docker-registry.gce-us-central1.travisci.net"
  - la -la /var/log
  - cat /var/log/docker.log
  #- sudo cat /etc/docker/daemon-direct-lvm.json
  #- sudo cat /etc/docker/registry-daemon.json
  #- sudo docker pull alpine

#script:
  #- ./sleep.sh $SLEEP
