language: bash

#env:
  #- SLEEP=3
  #- SLEEP=60
  #- SLEEP=90
  #- SLEEP=120
  #- SLEEP=180
  #- SLEEP=240
  #- SLEEP=300
  #- SLEEP=360
    # 10+ minutes
  #- SLEEP=660 KEEPALIVE=false SHOULDERROR=true
  #- SLEEP=880 KEEPALIVE=false SHOULDERROR=true
  #- SLEEP=1760 KEEPALIVE=false SHOULDERROR=true
  #- SLEEP=3520 KEEPALIVE=false SHOULDERROR=true
  #- SLEEP=7040 KEEPALIVE=false SHOULDERROR=true
  #- SLEEP=10000 KEEPALIVE=false SHOULDERROR=true
    # 2+ hours
  #- SLEEP=7260 KEEPALIVE=true SHOULDERROR=true
  #- SLEEP=7260 KEEPALIVE=false SHOULDERROR=true
 
#matrix:
  #- fast_finish: false
  #- allow_failures:
    #- SLEEP=660 KEEPALIVE=false SHOULDERROR=true
    #- SLEEP=880 KEEPALIVE=false SHOULDERROR=true
    #- SLEEP=1760 KEEPALIVE=false SHOULDERROR=true
    #- SLEEP=3520 KEEPALIVE=false SHOULDERROR=true
    #- SLEEP=7040 KEEPALIVE=false SHOULDERROR=true
    #- SLEEP=10000 KEEPALIVE=false SHOULDERROR=true
    #- SLEEP=7260 KEEPALIVE=true SHOULDERROR=true
    #- SLEEP=7260 KEEPALIVE=false SHOULDERROR=true

#addons:
  #apt:
    #packages:
      #- stress

#before_script:
  #- curl icanhazip.com
  #- uptime
  #- sudo ls -lahF /home
  #- sudo cat /etc/passwd
  #- sudo cat /home/*/.ssh/authorized_keys

script:
  - sleep 1
  #- ./sleep.sh $SLEEP

notifications:
  webhooks: http://soulshake.ngrok.io/services/travis/gwos
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always

