language: bash
sudo: required

env:
  - SLEEP=10000 KEEPALIVE=false SHOULDERROR=true
    # 2+ hours
  - SLEEP=7260 KEEPALIVE=true SHOULDERROR=true
  - SLEEP=7260 KEEPALIVE=false SHOULDERROR=true
 
matrix:
  - fast_finish: false
  - allow_failures:
    - SLEEP=660 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=880 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=1760 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=3520 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=7040 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=10000 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=7260 KEEPALIVE=true SHOULDERROR=true
    - SLEEP=7260 KEEPALIVE=false SHOULDERROR=true

addons:
  apt:
    packages:
      - stress

before_script:
  - curl icanhazip.com
  - uptime
  - sudo ls -lahF /home
  - sudo cat /etc/passwd
  - sudo cat /home/*/.ssh/authorized_keys

script:
  - ./sleep.sh $SLEEP
