language: bash
sudo: required

#env:
  #- SLEEP=10000 KEEPALIVE=false SHOULDERROR=true
    # 2+ hours
  #- SLEEP=7260 KEEPALIVE=true SHOULDERROR=true
  #- SLEEP=7260 KEEPALIVE=false SHOULDERROR=true

before_script:
  - sudo docker info
  - sudo cat /etc/default/docker
  - /etc/init.d/docker status
  - ls -la /etc/init.d
  - sudo ls -lahF /etc/docker
  - ps -fp $(pidof dockerd)
  - sudo cat /etc/docker/daemon-direct-lvm.json
  - sudo cat /etc/docker/registry-daemon.json
  - sudo docker pull alpine

#script:
  #- ./sleep.sh $SLEEP
