language: bash
sudo: required

#env:
  #- SLEEP=10000 KEEPALIVE=false SHOULDERROR=true
    # 2+ hours
  #- SLEEP=7260 KEEPALIVE=true SHOULDERROR=true
  #- SLEEP=7260 KEEPALIVE=false SHOULDERROR=true

before_script:
  - sudo docker info
  - sudo docker info | grep -i mirror
  - sudo ls -lahF /etc/docker
  - ps -fp $(pidof dockerd)
  - sudo cat /var/log/upstart/docker.log
  - sudo docker pull alpine

#script:
  #- ./sleep.sh $SLEEP
