language: bash
env:
  - SLEEP=60
  - SLEEP=120
  - SLEEP=240
  - SLEEP=880 KEEPALIVE=true
  - SLEEP=880 KEEPALIVE=false SHOULDERROR=true

matrix:
  fast_finish: true
  allow_failures:
    - env: SHOULDERROR=true

script: ./sleep.sh $SLEEP
