language: bash
env:
  - SLEEP=60
  - SLEEP=120
  - SLEEP=240
  - SLEEP=880 KEEPALIVE=true
  - SLEEP=880 KEEPALIVE=false SHOULDERROR=true
  - SLEEP=1760 KEEPALIVE=true
  - SLEEP=1760 KEEPALIVE=false SHOULDERROR=true

matrix:
  fast_finish: false
  allow_failures:
    - SLEEP=880 KEEPALIVE=false SHOULDERROR=true
    - SLEEP=1760 KEEPALIVE=false SHOULDERROR=true

script: ./sleep.sh $SLEEP
