language: bash
sudo: required

#env:
  #- SLEEP=10000 KEEPALIVE=false SHOULDERROR=true
    # 2+ hours
  #- SLEEP=7260 KEEPALIVE=true SHOULDERROR=true
  #- SLEEP=7260 KEEPALIVE=false SHOULDERROR=true

before_script:
  - sudo docker info
  - sudo cat /etc/default/docker
  - sudo docker pull alpine

#script:
  #- ./sleep.sh $SLEEP
